apiVersion: configobserver.example.com/v1
kind: ConfigObserver
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder-configobserver
    app.kubernetes.io/managed-by: kustomize
  name: configobserver-sample
spec:
  # TODO(user): Add fields here
